@startuml SequenceFilterNews

actor "Người dùng" as user
boundary "UI: Trang chủ" as ui_main
control "Ctrl: Quản lý bài báo" as ctrl_article
control "Ctrl: Cache dữ liệu" as ctrl_cache
entity "Bộ nhớ cục bộ" as repository

activate user
user -> ui_main: Truy cập màn hình tin tức

activate ui_main
ui_main -> ctrl_article: Yêu cầu danh sách tin tức
activate ctrl_article

ctrl_article -> ctrl_cache: Kiểm tra cache
activate ctrl_cache
ctrl_cache --> ctrl_article: Dữ liệu cache (nếu có)
deactivate ctrl_cache

alt#Gold #LightGreen Cache không có hoặc hết hạn
    ctrl_article -> repository: Lấy tin tức từ nguồn
    activate repository
    repository --> ctrl_article: Danh sách tin tức
    deactivate repository
    
    ctrl_article -> ctrl_cache: Lưu vào cache
    activate ctrl_cache
    deactivate ctrl_cache
end

ctrl_article --> ui_main: Danh sách tin
deactivate ctrl_article

ui_main --> user: Hiển thị tin tức

user -> ui_main: Chọn thẻ danh mục/thời gian
ui_main -> ctrl_article: Yêu cầu lọc
activate ctrl_article

ctrl_article -> ctrl_article: Lọc tin tức
ctrl_article --> ui_main: Tin tức đã lọc
deactivate ctrl_article

ui_main --> user: Hiển thị tin tức của danh mục


alt#Gold #Pink Không có tin tức phù hợp
    ui_main --> user: "Không có tin tức với bộ lọc này"

deactivate ui_main
deactivate user

@enduml
